# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.46.0"
catpuccin = "1.11.0"
"which-key.nvim" = "3.17.0"
"mason.nvim" = "2.0.1"
nvim-lspconfig = "2.4.0"
"mason-lspconfig.nvim" = "2.1.0"
"rocks-treesitter.nvim" = "1.3.1"
"rocks-edit.nvim" = "scm"
"rocks-config.nvim" = "3.1.2"
"oil.nvim" = "2.15.0"
# "rocks-lazy.nvim" = "1.2.2"

[config]
plugins_dir = "plugins/"
